### ISSUE TITLE
Unable to compile: error[E0554]: `#![feature]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by xbsd** [redsift/kdb-rs-hash#1]
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/name/.cargo/registry/src/github.com-1ecc6299db9ec823/rkdb-0.2.0/src/lib.rs:1:1
  |
1 | #![feature(lang_items, box_patterns)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
For more information about this error, try `rustc --explain E0554`.
error: could not compile `rkdb` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `rkdb` due to previous error

**Comment by AnthonyMichaelTDM** [comment]
you need to use the nightly toolchain
